TarkariWala/Models/Supplier.cs
namespace TarkariWala.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int SuppliersID { get; set; }

        [StringLength(50)]
        public string SuppliersName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

TarkariWala/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TarkariWala.Models;

namespace TarkariWala.Controllers
{
    public class SuppliersController : Controller
    {
        private Tarkari db = new Tarkari();

        // GET: Suppliers
        public ActionResult Index()
        {
            return View(db.Suppliers.ToList());
        }

        public ActionResult ProductDetails(int? id)
        {
            var all = db.Suppliers.Where(p=>p.SuppliersID == id).ToList();
            return View(all);
        }

        // GET: Suppliers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SuppliersID,SuppliersName")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Suppliers.Add(supplier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SuppliersID,SuppliersName")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = db.Suppliers.Find(id);
            db.Suppliers.Remove(supplier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TarkariWala/Views/Suppliers/Create.cshtml
@model TarkariWala.Models.Supplier

@{
    ViewBag.Title = "Create";
}
    <div>
        <div class="bg-dark">
            <p class="nav-link text-white" style="font-size:20px;"> Suppliers &nbsp;<i class="fas fa-chevron-right"></i> Create</p>
        </div>
        <div>
            <ul class="nav nav-tabs" id="tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active btn-outline-info" id="create-tab" data-toggle="tab" href="#SuppliersCreate" role="tab" aria-controls="create" aria-selected="true">Create</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-outline-info" id="index-tab" data-toggle="tab" href="#SuppliersIndex" role="tab" aria-controls="index" aria-selected="true">Index</a>
                </li>
            </ul>
        </div>
        <div class="tab-content" id="productstabcontent">
            <div class="tab-pane fade show active" id="SuppliersCreate" role="tabpanel" aria-labelledby="create-tab">
                <br />

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="wrapper">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.SuppliersName, htmlAttributes: new { @class = "control-label col-md-2" })
                                        </div>
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.SuppliersName, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.SuppliersName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                }
            </div>

            <div id="SuppliersIndex" class="tab-pane fade" role="tabpanel" aria-labelledby="index-tab">
                @Html.Action("Index", "Suppliers")

            </div>
        </div>
    </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

TarkariWala/Views/Suppliers/Delete.cshtml
@model TarkariWala.Models.Supplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SuppliersName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SuppliersName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TarkariWala/Views/Suppliers/Details.cshtml
@model TarkariWala.Models.Supplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SuppliersName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SuppliersName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SuppliersID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TarkariWala/Views/Suppliers/Edit.cshtml
@model TarkariWala.Models.Supplier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Supplier</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SuppliersID)

        <div class="form-group">
            @Html.LabelFor(model => model.SuppliersName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SuppliersName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SuppliersName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TarkariWala/Views/Suppliers/Index.cshtml
@model IEnumerable<TarkariWala.Models.Supplier>

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div class="container">
    <table class="table" id="supplierstable" border="1">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SuppliersName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="javascript:void(0);" class="clickmeEvent text-primary" data-id="@item.SuppliersID"> @item.SuppliersName</a>
                        <p id="suppliersName" hidden>@item.SuppliersName</p>
                        
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.SuppliersID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.SuppliersID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.SuppliersID })
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr></tr>
        </tfoot>

    </table>
</div>

<div id='myModal' class='modal'>
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <i class="fas fa-tasks"></i> &nbsp;<span id="suppliersName1"></span>
            </div>
            <div id='myModalContent'>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
    
</div>
<link href="~/Content/datatable jq/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Content/datatable jq/jquery.dataTables.min.js"></script>
    <script>
       
        $(document).ready(function () {
            $('#supplierstable').DataTable({

            });

            var TeamDetailPostBackURL = '/Suppliers/ProductDetails';

            $(".clickmeEvent").click(function () {
                alert();
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: TeamDetailPostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        $('#myModal').modal('show');


                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    },
                });
            });
        });
    </script>
}

TarkariWala/Views/Suppliers/ProductDetails.cshtml
@model IEnumerable<TarkariWala.Models.Supplier>
@{
    ViewBag.Title = "ProductDetails";
}

<h2>SuppliersDetails</h2>
<div>
    
    <hr />
    <table class="table" id="suppliersdetailproduct" border="1">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SuppliersName)
                </th>
                <th></th>
            </tr>

        </thead>
        <tbody>
            @foreach (var items in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => items.SuppliersName)
                    </td>
                    
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = items.SuppliersID }) |
                        @Html.ActionLink("Back to List", "Index")
                    </td>
                </tr>
            }

        </tbody>
        <tfoot></tfoot>
    </table>
</div>
<link href="~/Content/datatable jq/jquery.dataTables.min.css" rel="stylesheet" />

    @section scripts{
        <script src="~/Content/datatable jq/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready(function () {
                $('#productdetailstable').DataTable({

                });
            });
        </script>
    }